# Generated by Django 5.1.2 on 2025-02-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_qr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='height',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='width',
        ),
        migrations.AddField(
            model_name='qr',
            name='img',
            field=models.ImageField(null=True, upload_to='media/qr/img'),
        ),
        migrations.AlterField(
            model_name='qr',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
