# Generated by Django 5.1.2 on 2025-02-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_qr', '0002_remove_qr_height_remove_qr_shape_remove_qr_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='img',
            field=models.ImageField(null=True, upload_to='qr/img'),
        ),
    ]
