# Generated by Django 5.1.2 on 2025-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_qr', '0004_qr_date_qr_shape_qr_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='img',
            field=models.ImageField(default=False, upload_to='qr/img'),
            preserve_default=False,
        ),
    ]
