# Generated by Django 5.1.2 on 2025-02-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_qr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QR',
        ),
    ]
